export const data = [
    {
        id: "qshshQSQsa",
        title: "Love in the Time of Cholera",
        author: "Gabriel Garcia Marquez",
        img: "https://flxt.tmsimg.com/assets/p170019_p_v8_al.jpg",
        rate: 9,
        price: 50,
    },
    {
        id: "WXserygBNU",
        title: "One Hundred Years of Solitude",
        author: "Gabriel Garcia Marquez",
        img: "https://m.media-amazon.com/images/I/71IWwBoDNsL.jpg",
        rate: 8,
        price: 35,
    },
    {
        id: "pdlZygBNUo",
        title: "Hamlet",
        author: "William Shakespeare",
        img: "https://kbimages1-a.akamaihd.net/695eb39e-9405-4c4b-8267-302344f0f5f7/1200/1200/False/hamlet-15.jpg",
        rate: 9,
        price: 45,
    },
    {
        id: "UydhHpoXwq",
        title: "Misery",
        author: "Stephen King",
        img: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781501156748/misery-9781501156748_hr.jpg",
        rate: 7,
        price: 30,
    },
    {
        id: "TyUhnSDfgP",
        title: "Waiting for Godot: Tragicomedy in 2 Acts",
        author: "Samuel Beckett",
        img: "https://m.media-amazon.com/images/I/410gnFMui1L._AC_SY780_.jpg",
        rate: 9,
        price: 40,
    },
    {
        id: "MlnvFDsrTy",
        title: "Nineteen Eighty-Four",
        author: "George Orwell",
        img: "https://kbimages1-a.akamaihd.net/c9472126-7f96-402d-ba57-5ba4c0f4b238/1200/1200/False/nineteen-eighty-four-1984-george.jpg",
        rate: 8,
        price: 40,
    },
    {
        id: "cWXGHjkido",
        title: "The Lovely Bones",
        author: "Alice Sebold",
        img: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1457810586l/12232938.jpg",
        rate: 6,
        price: 20,
    },
    {
        id: "LPfghSWaet",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        img: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320399351l/1885.jpg",
        rate: 6,
        price: 25,
    },
];
